cdef extern from "pyResLevelPool.h":
    void c_levelpool_physics(double *dt,
                              double *qi0,
                              double *qi1,
                              double *ql,
                              double *ar,
                              double *we,
                              double *maxh,
                              double *wc,
                              double *wl,
                              double *dl,
                              double *oe,
                              double *oc,
                              double *oa,
                              double *H0,
                              double *H1,
                              double *qo1) nogil;

cdef extern from "pyMCsingleSegStime_NoLoop.h":
    void c_muskingcungenwm(double *dt,
                                  double *qup,
                                  double *quc,
                                  double *qdp,
                                  double *ql,
                                  double *dx,
                                  double *bw,
                                  double *tw,
                                  double *twcc,
                                  double *n,
                                  double *ncc,
                                  double *cs,
                                  double *s0,
                                  double *velp,
                                  double *depthp,
                                  double *qdc,
                                  double *velc,
                                  double *depthc,
                                  double *ck,
                                  double *cn,
                                  double *X) nogil;
    
cdef extern from "pydiffusive.h":
    void c_diffnw(double *dtini_g,
                     double *t0_g,
                     double *tfin_g,
                     double *saveinterval_g,
                     double *saveinterval_ev_g,
                     double *dt_ql_g,
                     double *dt_ub_g,
                     double *dt_db_g,
                     int *nts_ql_g,
                     int *nts_ub_g,
                     int *nts_db_g,
                     int *mxncomp_g,
                     int *nrch_g,
                     double *z_ar_g,
                     double *bo_ar_g,
                     double *traps_ar_g,
                     double *tw_ar_g,
                     double *twcc_ar_g,
                     double *mann_ar_g,
                     double *manncc_ar_g,
                     double *so_ar_g,
                     double *dx_ar_g,
                     double *iniq,
                     int *nhincr_m_g,
                     int *nhincr_f_g,
                     double *ufhlt_m_g,
                     double *ufqlt_m_g,
                     double *ufhlt_f_g,
                     double *ufqlt_f_g,
                     int *frnw_col,
                     double *frnw_g,
                     double *qlat_g,
                     double *ubcd_g,
                     double *dbcd_g,
                     double *cfl_g,
                     double *theta_g,
                     int *tzeq_flag_g,
                     int *y_opt_g,
                     double *so_llm_g,
                     int *ntss_ev_g,
                     double *q_ev_g,
                     double *elv_ev_g) nogil;


