extern void c_muskingcungenwm(double *dt,
                              double *qup,
                              double *quc,
                              double *qdp,
                              double *ql,
                              double *dx,
                              double *bw,
                              double *tw,
                              double *twcc,
                              double *n,
                              double *ncc,
                              double *cs,
                              double *s0,
                              double *velp,
                              double *depthp,
                              double *qdc,
                              double *velc,
                              double *depthc,
                              double *ck,
                              double *cn,
                              double *X);

