extern void c_levelpool_physics(double *dt,
                              double *qi0,
                              double *qi1,
                              double *ql,
                              double *ar,
                              double *we,
                              double *maxh,
                              double *wc,
                              double *wl,
                              double *dl,
                              double *oe,
                              double *oc,
                              double *oa,
                              double *H0,
                              double *H1,
                              double *qo1);
